### ISSUE TITLE
UnboundLocalError with paginatesects.py filter

### ISSUE THREAD

**Issue by dnebauer** [msprev/dot-panzer#7]
The filter `paginatesects.py` quite properly throws an UnboundLocalError on the `insert` variable under python 3.6.4 because `insert` is defined in an `if` block but used *outside* the `if` block. Python correctly understands that if the `if` block is never entered the `insert` variable will never be defined, and so will cause an error when subsequently called. The error is fixed by initialising `insert` before entering the `if` block.

I haven't checked whether other filters in this repo have the same structure. I also haven't tested on earlier versions of python (where I presume this error was not triggered or it would have been detected by now).

Thanks for panzer -- it's brilliant. And this repo of dotfiles was a giant help in understanding how panzer works.

**Comment by msprev** [comment]
Thank you very much for the kind words. It makes it all worthwhile.

I've pushed a fix for this now, and it should work. 

I confess that I'm not proud of much of the code in the filters directory here -- I tended to bash out a filter pretty quickly to solve a particular problem and didn't go back to revise and maintain the code later unless I had to to. I recently cleaned up the templates massively, and I need to do the same with the filters. I'm glad you've found this repo useful to demonstrate what panzer can do.

**Comment by dnebauer** [comment]
Commit `4f1c0c9` resulted in `paginatesects.py` having these return commands:

```py
return [RawInline('latex', text), Header(value[0], value[1], value[2])]
# ...
return [RawInline('html', text), Header(value[0], value[1], value[2])]
```

Using this version of the file resulted in fatal JSON parse errors.

I changed these return commands to resemble the previous syntax, i.e., wrap the `RawInline` in a `Para` element:

```py
return [Para([RawInline('latex', text)]),
        Header(value[0], value[1], value[2])]
# ...
return [Para([RawInline('html', text)]),
        Header(value[0], value[1], value[2])]
```

That version of the script worked.

**Comment by msprev** [comment]
Thank you! I've pushed the fix to the repo now.

**Comment by dnebauer** [comment]
You have a cut and paste artefact: the `latex` format is specified for both latex *and html*. The `return` statement for html format needs to be changed to:

```py
return [Para([RawInline('html', text)]), Header(value[0], value[1], value[2])]
```

**Comment by msprev** [comment]
That'll teach me. I've pushed the correct fix now. Thank you!
