### ISSUE TITLE
Filter Explanations?

### ISSUE THREAD

**Issue by jacksonkernion** [msprev/dot-panzer#8]
I'm setting up my Panzer workflow and it looks like there's a lot of great stuff in here! But it was a bit tough for me to figure out what exactly these scripts did/whether it worth copying them for my own use. Mind adding a section in the Readme explaining (in a sentence or two) what each script does?

**Comment by msprev** [comment]
Thanks! Each filter should have a brief explanation of what it does at the top of its source code. I threw the filters together pretty quickly to solve problems for me so may not be flexible enough for everyone. Hopefully they should be easy to adapt though.

**Comment by jacksonkernion** [comment]
Ah, got it. Thanks!
